name = "stagios-ft-proxy"
main = "ft-proxy.js"
compatibility_date = "2024-09-01"

# Les secrets NE sont PAS dans ce fichier.
# Utilise :
#   wrangler secret put FT_CLIENT_ID
#   wrangler secret put FT_CLIENT_SECRET
